### ISSUE TITLE
missing fix_repo (npm out of the box)

### ISSUE THREAD

**Issue by lightTrader** [TimelordUK/jspurefix#26]
output from a simple app using package via npm (like jspf-demo), seems like something not been unzipped or included in node_modules dist. (npm run unzip-repo - cmd was not found) 

root@localhost:/pitt# node dist/app.js
2021-12-05T03:59:13.169Z [test-launcher] info: launching ..
2021-12-05T03:59:13.172Z [test-launcher] info: launching ..
2021-12-05T03:59:13.175Z [test-launcher] error: ENOENT: no such file or directory, lstat '/pitt/node_modules/jspurefix/data/fix_repo/FIX.4.4/Base' : Error: ENOENT: no such file or directory, lstat '/pitt/node_modules/jspurefix/data/fix_repo/FIX.4.4/Base'
    at Object.lstatSync (fs.js:1077:3)
    at /pitt/node_modules/jspurefix/dist/util/dictionary-definitions.js:31:16
    at Generator.next (<anonymous>)
    at /pitt/node_modules/jspurefix/dist/util/dictionary-definitions.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/pitt/node_modules/jspurefix/dist/util/dictionary-definitions.js:4:12)
    at getDefinitions (/pitt/node_modules/jspurefix/dist/util/dictionary-definitions.js:24:12)
    at Object.<anonymous> (/pitt/node_modules/jspurefix/dist/transport/make-config.js:20:69)
    at Generator.next (<anonymous>)
    at /pitt/node_modules/jspurefix/dist/transport/make-config.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/pitt/node_modules/jspurefix/dist/transport/make-config.js:4:12)
    at /pitt/node_modules/jspurefix/dist/transport/make-config.js:18:48
    at new Promise (<anonymous>)
    at Object.<anonymous> (/pitt/node_modules/jspurefix/dist/transport/make-config.js:18:16)
    at Generator.next (<anonymous>)
    at /pitt/node_modules/jspurefix/dist/transport/make-config.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/pitt/node_modules/jspurefix/dist/transport/make-config.js:4:12)
    at Object.makeConfig (/pitt/node_modules/jspurefix/dist/transport/make-config.js:17:12)
    at AppLauncher.setup (/pitt/dist/session/launcher.js:32:48)
    at /pitt/dist/session/launcher.js:18:18
(node:44190) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/pitt/node_modules/jspurefix/data/fix_repo/FIX.4.4/Base'
    at Object.lstatSync (fs.js:1077:3)

**Comment by TimelordUK** [comment]
https://ci.appveyor.com/project/TimelordUK/jspf-demo/build/job/ukqyet2ff8x30l0k

seems to run fine on appveyor

**Comment by lightTrader** [comment]
on the readme it's missing 'cd node_modules/jspurefix'  prior  to running  'npm run unzip-repo'
all okay
