### ISSUE TITLE
URGENT: Message Field Ordering

### ISSUE THREAD

**Issue by pakheili** [TimelordUK/jspurefix#77]
Hi @TimelordUK. Great work on this library, thank you very much.

I hope this message finds you well. We have been utilising the library for managing FIX messages and have encountered a specific issue regarding the ordering of fields (tags) within the message body. Currently, the library appears to sort the fields in a standard order, which does not have the flexibility to handle unsorted fields in a message.

The problem arises when our clients send market data request messages, where the order of the fields in the message body is as follows: `49,56,34,52,262,263,264,146,461,55` (**the positions of tags 461 and 55 are swapped**). We reject this order because it does not follow the standard order. 

However, the library accepts the order of the fields as `49,56,34,52,262,263,264,146,55,461`.

Below is the standard ordered message that the client sends us and they successfully receive market data:
```
8 (BeginString) =FIX.4.4
9 (BodyLength) =0000115
35 (MsgType) =V
49 (SenderCompID) =sender
56 (TargetCompID) =target
34 (MsgSeqNum) =3
52 (SendingTime) =20231108-09:40:46.257
262 (MDReqID) =1698937860913.38
263 (SubscriptionRequestType) =1
264 (MarketDepth) =85
146 (NoRelatedSym) =1
55 (Symbol) =*
461 (CFICode) =O
10 (CheckSum) =033
```

To address this issue, we kindly request your guidance on the following matters:

1. **Automatic Sorting:** Is there a built-in mechanism within the library that can be utilised to automatically sort the various fields within the three components (header, body, trailer) of messages by tag number before receiving a request message in a session? If so, could you provide us with documentation or guidance on how to achieve this behaviour?

2. **Field Ordering Customisation:** Can we customise the order of the fields in a message sent to our acceptor using the library? If such customisation is possible, we would appreciate any insights or instructions on how to achieve this flexibility.

3. **Preventing Sorting Behaviour:** In case the sorting behaviour is a default behaviour of the library, is there a way to prevent the automatic sorting of fields, ensuring that the order of fields in the message body remains unchanged? We would appreciate any guidance on this matter.

We value the functionality and reliability of the library and believe that addressing this issue or obtaining the requested information would greatly enhance our integration with the library.

Thank you for your assistance in advance. We look forward to your response and any guidance you can provide to help us resolve this matter.

**Comment by TimelordUK** [comment]
What error do we reject with out of interest. What is fix specification file you are using.  In theory we should not reject based on field order I’ll have to first reproduce this problem. We make two passes over a meaaage. First we simply mark where each field starts and end and we parse the tag. Then we send it through a segment parser where each tag is checked and we add structure.  For example if a field belongs in instrument we start an instrument segment. We sort the message fields at end when for example you ask for a certain field it can be searched with binary search.  All structure is known even after this so we know where everything was. Can you send exact message transactions you can remove the header for confidentiality if you wish I’d like to see exactly what error is sent. Sent from my iPhoneOn 8 Nov 2023, at 11:29, Pak Hei Li ***@***.***> wrote:﻿
Hi @TimelordUK. Great work on this library, thank you very much.
I hope this message finds you well. We have been utilising the library for managing FIX messages and have encountered a specific issue regarding the ordering of fields (tags) within the message body. Currently, the library appears to sort the fields in a standard order, which does not have the flexibility to handle unsorted fields in a message.
The problem arises when our clients send market data request messages, where the order of the fields in the message body is as follows: 49,56,34,52,262,263,264,146,461,55 (the positions of tags 461 and 55 are swapped). We reject this order because it does not follow the standard order.
However, the library accepts the order of the fields as 49,56,34,52,262,263,264,146,55,461.
Below is the standard ordered message that the client sends us and they successfully receive market data:
8 (BeginString) =FIX.4.4
9 (BodyLength) =0000115
35 (MsgType) =V
49 (SenderCompID) =sender
56 (TargetCompID) =target
34 (MsgSeqNum) =3
52 (SendingTime) =20231108-09:40:46.257
262 (MDReqID) =1698937860913.38
263 (SubscriptionRequestType) =1
264 (MarketDepth) =85
146 (NoRelatedSym) =1
55 (Symbol) =*
461 (CFICode) =O
10 (CheckSum) =033

To address this issue, we kindly request your guidance on the following matters:


Automatic Sorting: Is there a built-in mechanism within the library that can be utilised to automatically sort the various fields within the three components (header, body, trailer) of messages by tag number before receiving a request message in a session? If so, could you provide us with documentation or guidance on how to achieve this behaviour?


Field Ordering Customisation: Can we customise the order of the fields in a message sent to our acceptor using the library? If such customisation is possible, we would appreciate any insights or instructions on how to achieve this flexibility.


Preventing Sorting Behaviour: In case the sorting behaviour is a default behaviour of the library, is there a way to prevent the automatic sorting of fields, ensuring that the order of fields in the message body remains unchanged? We would appreciate any guidance on this matter.


We value the functionality and reliability of the library and believe that addressing this issue or obtaining the requested information would greatly enhance our integration with the library.
Thank you for your assistance in advance. We look forward to your response and any guidance you can provide to help us resolve this matter.

**Comment by TimelordUK** [comment]
I should add when sending a message it should be formatted exactly as declared in specification. The engine will go through each field one at a time and if present will send that field at that position. If you for example change the ordering in the xml file the engine from acceptor to client should send the message in that order. Sent from my iPhoneOn 8 Nov 2023, at 18:54, Stephen James ***@***.***> wrote:﻿What error do we reject with out of interest. What is fix specification file you are using.  In theory we should not reject based on field order I’ll have to first reproduce this problem. We make two passes over a meaaage. First we simply mark where each field starts and end and we parse the tag. Then we send it through a segment parser where each tag is checked and we add structure.  For example if a field belongs in instrument we start an instrument segment. We sort the message fields at end when for example you ask for a certain field it can be searched with binary search.  All structure is known even after this so we know where everything was. Can you send exact message transactions you can remove the header for confidentiality if you wish I’d like to see exactly what error is sent. Sent from my iPhoneOn 8 Nov 2023, at 11:29, Pak Hei Li ***@***.***> wrote:﻿
Hi @TimelordUK. Great work on this library, thank you very much.
I hope this message finds you well. We have been utilising the library for managing FIX messages and have encountered a specific issue regarding the ordering of fields (tags) within the message body. Currently, the library appears to sort the fields in a standard order, which does not have the flexibility to handle unsorted fields in a message.
The problem arises when our clients send market data request messages, where the order of the fields in the message body is as follows: 49,56,34,52,262,263,264,146,461,55 (the positions of tags 461 and 55 are swapped). We reject this order because it does not follow the standard order.
However, the library accepts the order of the fields as 49,56,34,52,262,263,264,146,55,461.
Below is the standard ordered message that the client sends us and they successfully receive market data:
8 (BeginString) =FIX.4.4
9 (BodyLength) =0000115
35 (MsgType) =V
49 (SenderCompID) =sender
56 (TargetCompID) =target
34 (MsgSeqNum) =3
52 (SendingTime) =20231108-09:40:46.257
262 (MDReqID) =1698937860913.38
263 (SubscriptionRequestType) =1
264 (MarketDepth) =85
146 (NoRelatedSym) =1
55 (Symbol) =*
461 (CFICode) =O
10 (CheckSum) =033

To address this issue, we kindly request your guidance on the following matters:


Automatic Sorting: Is there a built-in mechanism within the library that can be utilised to automatically sort the various fields within the three components (header, body, trailer) of messages by tag number before receiving a request message in a session? If so, could you provide us with documentation or guidance on how to achieve this behaviour?


Field Ordering Customisation: Can we customise the order of the fields in a message sent to our acceptor using the library? If such customisation is possible, we would appreciate any insights or instructions on how to achieve this flexibility.


Preventing Sorting Behaviour: In case the sorting behaviour is a default behaviour of the library, is there a way to prevent the automatic sorting of fields, ensuring that the order of fields in the message body remains unchanged? We would appreciate any guidance on this matter.


We value the functionality and reliability of the library and believe that addressing this issue or obtaining the requested information would greatly enhance our integration with the library.
Thank you for your assistance in advance. We look forward to your response and any guidance you can provide to help us resolve this matter.

**Comment by TimelordUK** [comment]
so i have written a test here  on fix 52 branch

note ordering as 461=0|55=GBPUSD|

we still seem to parse the message and see the instrument view. So im not sure the reason for the reject is down to rerversed fields - it is possible  the current rellease does behave this way

```ts
test('parse MD request with instrument 461=0||55=GBPUSD|', async () => {
  // const changed = logon.replace('108=62441|','000=62441|')
  const msg = '8=FIX.5.0SP2|9=0000145|35=V|49=init-comp|56=accept-comp|34=2|57=fix|52=20231108-20:13:54.831|262=#GBPUSD#0#|263=1|264=0|267=3|269=0|269=1|269=H|146=1|461=0|55=GBPUSD|10=109|'
  const res = await setup.client.parseText(msg)
  expect(res.view).toBeTruthy()
  const o = res.view?.toObject() as IMarketDataRequest
  const grp = o.InstrmtMDReqGrp?.NoRelatedSym ?? []
  expect(grp.length).toEqual(1)
  console.log(JSON.stringify(o, null, 4))
  expect(grp[0].Instrument).toEqual({
    Symbol: 'GBPUSD',
    CFICode: '0'
  })
})
```

**Comment by pakheili** [comment]
Hi @TimelordUK, thank you for your help and detailed response!

Here are some clarifications, and hopefully it will let you better understand our issue:

These are the Market Data Request messages that were sent by our client. I don't remember which one was it in the logs, but one of our client's messages returns an error because the `|461=0|55=*|` and `|55=*|461=0|` are swapped in positions and it returns an `unknown tag type 146` error message. Hence, I believe we rejected our client's message order because it does not follow the standard order.

### Market Data Request Message with `|461=0|55=*|`
```
8=FIX.4.4|9=0000115|35=V|49=init-comp|56=accept-comp|34=2|57=fix|52=20231108-09:40:46.257|262=1698937860913.38|263=1|264=0|267=3|269=0|269=1|269=H|146=1|461=0|55=*|10=033|
```

### Market Data Request Message with `|55=*|461=0|`
```
8=FIX.4.4|9=0000115|35=V|49=init-comp|56=accept-comp|34=2|57=fix|52=20231108-09:40:46.257|262=1698937860913.38|263=1|264=0|267=3|269=0|269=1|269=H|146=1|55=*|461=0|10=033|
```

### Server's Error Messages Upon Receiving Our Client's Market Data Request Message
```
info - {
    "timestamp": "2023-11-14T13:07:28.336Z",
    "level": "ERROR",
    "app_name": "FIXSERVER-POOL2-SPECTRAOPTIONCUTTEST3",
    "service": "FIXSERVER-POOL2-SPECTRAOPTIONCUTTEST3:FIXSESSION",
    "message": "unknown tag type 146",
    "data": {
        "error": "at Writable.write (node:internal/streams/writable:337:10)"
    }
}
```

```
info - {
    "timestamp": "2023-11-14T13:07:28.336Z",
    "level": "WARNING",
    "app_name": "FIXSERVER-POOL2-SPECTRAOPTIONCUTTEST3",
    "service": "FIXSERVER-POOL2-SPECTRAOPTIONCUTTEST3:FIXSESSION",
    "message": "rx error event: unknown tag type 146 Error: unknown tag type 146\n    at examine (/usr/fix-engine/node_modules/jspurefix/src/buffer/ascii/ascii-segment-parser.ts:88:17)\n    at discover (/usr/fix-engine/node_modules/jspurefix/src/buffer/ascii/ascii-segment-parser.ts:130:27)\n    at AsciiSegmentParser.parse (/usr/fix-engine/node_modules/jspurefix/src/buffer/ascii/ascii-segment-parser.ts:156:5)\n    at AsciiParser.getView (/usr/fix-engine/node_modules/jspurefix/src/buffer/ascii/ascii-parser.ts:183:62)\n    at AsciiParser.msg (/usr/fix-engine/node_modules/jspurefix/src/buffer/ascii/ascii-parser.ts:85:42)\n    at AsciiParser.parse (/usr/fix-engine/node_modules/jspurefix/src/buffer/ascii/ascii-parser.ts:168:14)\n    at Writable.write [as _write] (/usr/fix-engine/node_modules/jspurefix/src/buffer/ascii/ascii-parser.ts:56:16)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Writable.write (node:internal/streams/writable:337:10)"
}
```

**Comment by TimelordUK** [comment]
What XML file are you using on server for the data dictionary

**Comment by TimelordUK** [comment]
the problem i have currently is I can run that message through the 3.0.0 fix engine using FIX44.xml and it seems to work with these fields swapped.

```ts
const marketDataMsg = '8=FIX.4.4|9=0000170|35=V|49=init-comp|56=accept-comp|34=2|57=fix|52=20231108-09:40:46.257|262=1698937860913.38|263=1|264=0|267=3|269=0|269=1|269=H|146=1|461=O|55=*|10=033|'

```

```json
 {
        "StandardHeader": {
            "BeginString": "FIX.4.4",
            "BodyLength": 170,
            "MsgType": "V",
            "SenderCompID": "init-comp",
            "TargetCompID": "accept-comp",
            "MsgSeqNum": 2,
            "TargetSubID": "fix",
            "SendingTime": "2023-11-08T09:40:46.257Z"
        },
        "MDReqID": "1698937860913.38",
        "SubscriptionRequestType": "1",
        "MarketDepth": 0,
        "MDReqGrp": {
            "NoMDEntryTypes": [
                {
                    "MDEntryType": "0"
                },
                {
                    "MDEntryType": "1"
                },
                {
                    "MDEntryType": "H"
                }
            ]
        },
        "InstrmtMDReqGrp": {
            "NoRelatedSym": [
                {
                    "Instrument": {
                        "Symbol": "*",
                        "CFICode": "O"
                    }
                }
            ]
        },
        "StandardTrailer": {
            "CheckSum": "033"
        }
    }
```

can you try and run a test client where for that client (leave server exactly as it is) you change the FIX44.xml file around line 2430 switch the two fields in question.  Then run your test sending a test message to the server and your test should then send like your client is sending with fields reversed.

Does that then cause this exception.

This doesnt  look like an easy fix we have to understand exactly what is going on.

if you can reproduce the problem that would be a start.  Clearly I see you are seeing this exception in the log the trouble is I cannot reproduce it.  

```xml
 <component name='Instrument'>
   <field name='Symbol' required='N' />
   <field name='SymbolSfx' required='N' />
   <field name='SecurityID' required='N' />
   <field name='SecurityIDSource' required='N' />
   <component name='SecAltIDGrp' required='N' />
   <field name='Product' required='N' />
   <field name='CFICode' required='N' />
```

**Comment by TimelordUK** [comment]
out of interest how  many concurrent sessions would be running on same node instance i.e. how do you fan out the connections is it for example the case the node instance is under load.  Can problem be reproduced with a server with  no active connections and the test sent as above.

**Comment by TimelordUK** [comment]
@helloissacli picking this up again with **5.9.1**. Short version: I believe this is fixed, but probably not for the reason either of us thought at the time, so I would rather you confirm than have me close it on inference.

## Field ordering is not the cause

I re-ran your exact messages. Both orderings parse correctly and produce identical objects:

```
146=1|55=*|461=O|      ← dictionary order
146=1|461=O|55=*|      ← the ordering you reported as rejected
```

```json
"InstrmtMDReqGrp": [ { "Instrument": { "Symbol": "*", "CFICode": "O" } } ]
```

No exception, and `invalid()`, `missing()` and `undefinedForMsg()` are all clean on the swapped ordering — the checks an acceptor rejects on. Pinned as a regression test with your bytes.

That is consistent with what we saw at the time: when I wrote a test on the `fix 52` branch with the same swap, **it also parsed**. So field order alone never reproduced your reject, which is why this issue stalled.

## What I now think was happening

`unknown tag type 146` is thrown when the segment parser meets a tag its positional state does not expect. There is a much better fit for that than field ordering.

Until 5.9.0, every connection accepted by one listener shared a single `ParseBuffer` instance. Each parser had its own state — tag offsets, position — but the buffer underneath was common. `beginMessage()` calls `elasticBuffer.reset()`, so the moment one connection completed a message it rewound the buffer every other connection was mid-way through writing into.

Two things follow, and both match your report:

**It is not a timing race.** Node serialises the socket callbacks, so a chunk is parsed atomically. The trigger is one connection being *mid-message*, which happens whenever a FIX message straddles a TCP segment boundary. Logon and heartbeat messages fit in one segment and never fragment — which is why an isolated test never sees this. Market data messages fragment routinely.

**It is not rare either.** Sweeping every split point of your MarketDataRequest with a shared buffer, it corrupts at **170 of 170**. Once a connection is mid-message, any traffic on another destroys it. The result surfaces as a structural parse error against a message that is perfectly valid on its own.

You told us in #87 that you were "running multiple FIX sessions, connecting multiple clients to a server". So the deployment that hit this was precisely the configuration with no per-session parse isolation, publishing exactly the message sizes that fragment.

As of 5.9.1 every accepted connection gets its own parse and transmit buffers. Both behaviours are pinned in [`interleaved-parse-isolation.test.ts`](https://github.com/TimelordUK/jspurefix/blob/master/src/test/ascii/interleaved-parse-isolation.test.ts).

## What would settle it

I cannot reproduce your exact `unknown tag type 146` — the error text depends on where the split lands — so this remains a strong circumstantial fit rather than a proven one. If you are able to run 5.9.1 against the counterparty that triggered it, that would close it properly. If it recurs, the server log now carries far more: a census line of connected transports and claimed sessions whenever the population changes, and per-counterparty log prefixes.

Leaving this open until you have had a chance to look. Related work is in #153 and #87, and [jspf-demo](https://github.com/TimelordUK/jspf-demo) has `multi-client` and `dynamic` modes if you want to see the isolation working.
